version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    image: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  product-service:
    build:
      context: ./product-service
    image: product-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - rabbitmq

  order-service:
    build:
      context: ./order-service
    image: order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - rabbitmq
      - product-service

  customer-service:
    build:
      context: ./customer-service
    image: customer-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"