server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - JwtFilter
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - JwtFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - JwtFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
  actuator:
    endpoints:
      prometheus:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/