version: '3.8'

services:
  order-service:
    image: order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=order_user
      - SPRING_DATASOURCE_PASSWORD=order_password
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - order-db
      - rabbitmq

  order-db:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_password
    volumes:
      - order_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management  # You might need to adjust the tag
    # If you need to access the management UI or other ports, uncomment below
    # ports:
    #   - "5672:5672"  # AMQP port
    #   - "15672:15672" # Management UI

volumes:
  order_db_data: