version: '3.8'
services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - customer-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - sales-network

  customer-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=customerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - customer-data:/var/lib/postgresql/data
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge

volumes:
  customer-data: